### ISSUE TITLE
When deploying a network if you are too quick on calling warnet status you get an error

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/warnet#601]
Error:

```shell
Traceback (most recent call last):
  File "/Users/maxedwards/source/warnet/.venv/bin/warnet", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/maxedwards/source/warnet/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/src/warnet/status.py", line 60, in status
    _connected(end="\r")
  File "/Users/maxedwards/source/warnet/src/warnet/network.py", line 65, in _connected
    peerinfo = json.loads(_rpc(tank.metadata.name, "getpeerinfo", ""))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/src/warnet/bitcoin.py", line 45, in _rpc
    return run_command(cmd)
           ^^^^^^^^^^^^^^^^
  File "/Users/maxedwards/source/warnet/src/warnet/process.py", line 7, in run_command
    raise Exception(result.stderr)
Exception: error code: -28
error message:
Loading wallet...
command terminated with exit code 28
```

**Comment by pinheadmz** [comment]
threw a fix for this on to https://github.com/bitcoin-dev-project/warnet/pull/600

**Comment by pinheadmz** [comment]
https://github.com/bitcoin-dev-project/warnet/pull/600/commits/0203931dd4c444263720f3cdaeed5af75815f1c4
