### ISSUE TITLE
Warnet setup crashes on windows

### ISSUE THREAD

**Issue by mvuk** [bitcoin-dev-project/warnet#662]
Running windows 10 IoT edition 

```
Matthew@DESKTOP-MQEA6VH MINGW64 ~/dev/learn/warnet (main)
$ warnet setup
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Scripts\warnet.exe\__main__.py", line 7, in <module>
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\site-packages\warnet\project.py", line 321, in setup
    print("                    \u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e                   ")
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 20-48: character maps to <undefined>
```

**Comment by pinheadmz** [comment]
I'm going recommend you try running python on windows with the `PYTHONUTF8=1` environment variable (I recently had the same issue with bitcoin core test runner which uses emojis in file names 🙄 )

But I'm also going to close this for now since we just don't support windows yet and that overall issue is tracked in https://github.com/bitcoin-dev-project/warnet/issues/655
